# -*- coding: utf-8 -*-
# Heron-Agent:  HERON-DEV-RGR-014
# Heron-Step:   15
# Heron-Status: DRAFT
# Heron-Since:  0.1.0
# Heron-Layer:  test
# See docs/29-metadata-standard.md

"""
The build matrix against its baseline - what it must do, asserted.

    python tests/test_buildmatrix.py

WHAT IT PROVES
  1. THE MATRIX IS READ FROM THE PROPS, NOT MIRRORED. Retarget a fixture
     and the matrix follows it, symbols included.

  2. A RETARGET IS CAUGHT FIELD BY FIELD. Moving one release from net48 to
     net8.0-windows is reported as the three fields it actually moved, not
     as "2024 changed".

  3. A RELEASE ADDED AND A RELEASE DROPPED ARE BOTH CHANGES. Dropping one
     silently is the direction that costs a modeller an add-in.

  4. THE BASELINE IS NEVER REGENERATED BY ACCIDENT. Without --update a
     missing baseline is refused, and drift is refused rather than
     recorded.

  5. IT COMPILES NOTHING AND EDITS NOTHING BUT THE BASELINE.

  6. THE LIVE MATRIX AGREES WITH HERON-DEV-NET-006's OWN TABLES. Two
     derivations written separately from one props file; if they ever
     disagree, one of them is wrong and this says so before a build does.

  7. EVERY FAILURE THE CONTRACT DECLARES IS NAMED AND REACHED, read from
     the contract rather than typed here (PROPOSALS F27).
"""

import io
import json
import os
import shutil
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "brain"))

import heron_buildmatrix as RGR                            # noqa: E402
import heron_dotnet as NET                                     # noqa: E402
import heron_contract as CON                                   # noqa: E402

FAILURES = []
CHECKED = []

# A props file of the same shape as the real one, small enough to read.
# `&gt;=` is how MSBuild spells it, and reading that spelling is part of
# what is being proved.
PROPS = """<Project>
  <PropertyGroup>
    <HeronTfm Condition="'$(RevitVersion)' == '2020'">net472</HeronTfm>
    <HeronTfm Condition="'$(RevitVersion)' &gt;= '2021' AND '$(RevitVersion)' &lt;= '2024'">%s</HeronTfm>
  </PropertyGroup>
  <PropertyGroup>
    <DefineConstants>$(DefineConstants);REVIT$(RevitVersion)</DefineConstants>
    <DefineConstants Condition="'$(RevitVersion)' &gt;= '2024'">$(DefineConstants);REVIT2024_OR_GREATER</DefineConstants>
  </PropertyGroup>
</Project>
"""


def check(condition, what):
    CHECKED.append(what)
    print("  %-5s %s" % ("ok" if condition else "FAIL", what))
    if not condition:
        FAILURES.append(what)


def main():
    reached = set()
    where = tempfile.mkdtemp(prefix="heron-matrix-")
    props = os.path.join(where, "Directory.Build.props")
    golden = os.path.join(where, "matrix.json")

    def write_props(tfm):
        io.open(props, "w", encoding="utf-8").write(PROPS % tfm)

    def run(**kw):
        out = RGR.regression(golden=golden, props=props, **kw)
        if out.get("refused"):
            reached.add(out["refused"])
        return out

    try:
        print("\n1. the matrix is read from the props, not mirrored")
        write_props("net48")
        live = RGR.matrix(props)
        check(sorted(live["releases"]) == ["2020", "2021", "2022", "2023", "2024"],
              "five releases, exactly the ones the fixture targets")
        check(live["releases"]["2020"]["tfm"] == "net472",
              "2020 is net472, as the props say")
        check(live["releases"]["2024"]["symbols"]
              == ["REVIT2024", "REVIT2024_OR_GREATER"],
              "2024 carries both symbols, the conditional one included")
        check(live["releases"]["2023"]["symbols"] == ["REVIT2023"],
              "and 2023 carries only its own - the >= condition is read")

        print("\n2. a missing baseline is refused, not quietly written")
        out = run()
        check(out["refused"] == "NO_GOLDEN",
              "nothing to compare against is refused, never a pass")
        check(not os.path.exists(golden),
              "and the refusal wrote no baseline of its own")

        out = run(update=True)
        check(out["wrote"] is True and os.path.exists(golden),
              "--update records it, and says it did")
        check(out["fixedAnything"] is True,
              "and admits it changed something")
        check(run()["passed"] is True, "the next run agrees with it")

        print("\n3. a retarget is caught field by field")
        write_props("net8.0-windows")
        out = run()
        check(out["passed"] is False, "the matrix no longer matches")
        check(out["refused"] == "DRIFTED", "and it is refused as DRIFTED")
        moved = dict((one["field"], one) for one in out["changed"]
                     if one["release"] == "2024")
        check(sorted(moved) == ["dotnetMajor", "needsWindowsDesktop", "tfm"],
              "2024 moved in three named fields, not 'changed'")
        check(moved["tfm"]["was"] == "net48"
              and moved["tfm"]["now"] == "net8.0-windows",
              "with the before and the after both carried")
        check(moved["dotnetMajor"]["now"] == 8,
              "the .NET major is derived from the new target")
        check(moved["needsWindowsDesktop"]["now"] is True,
              "and so is needing the WindowsDesktop targets")
        check("2020" in out["same"], "a release that did not move is untouched")

        print("\n4. an added release and a dropped one are both changes")
        write_props("net48")
        run(update=True)
        io.open(props, "w", encoding="utf-8").write(
            PROPS.replace("'2020'", "'2019'") % "net48")
        out = run()
        check("2019" in out["added"], "a newly targeted release is reported")
        check("2020" in out["removed"],
              "and one no longer targeted is reported, never dropped in silence")
        check(out["passed"] is False, "either one fails the comparison")

        print("\n5. it compiles nothing, and edits nothing but the baseline")
        write_props("net48")
        run(update=True)
        before = io.open(props, encoding="utf-8").read()
        out = run()
        check(out["ranAnything"] is False, "ranAnything is false - no SDK, no build")
        check(out["fixedAnything"] is False, "and a comparison fixes nothing")
        check(io.open(props, encoding="utf-8").read() == before,
              "the props file is byte-for-byte unchanged")
        source = io.open(os.path.join(ROOT, "brain",
                                      "heron_buildmatrix.py"),
                         encoding="utf-8").read()
        logic = source.split('"""', 2)[2]
        check("subprocess" not in logic,
              "nothing in it starts a process, so nothing in it compiles")
        check("have_dotnet" not in logic and "installed_sdks" not in logic,
              "and it probes no SDK - what a MACHINE has changes between "
              "machines and must never reach a committed baseline")

        print("\n6. it agrees with HERON-DEV-NET-006's own tables")
        real = RGR.matrix()
        check(sorted(real["releases"]) == sorted(NET.RELEASES),
              "the props and RELEASES name the same releases")
        for release, one in sorted(real["releases"].items()):
            check(one["needsWindowsDesktop"]
                  == (release in NET.NEEDS_WINDOWS_DESKTOP),
                  "%s needs the desktop targets: both derivations agree"
                  % release)
            check(one["dotnetMajor"] == NET.MINIMUM_DOTNET_MAJOR.get(release),
                  "%s .NET major: both derivations agree" % release)

        print("\n7. every failure the contract declares is reached")
        io.open(golden, "w", encoding="utf-8").write("not json at all")
        out = run()
        check(out["refused"] == "NOT_A_GOLDEN",
              "a baseline nothing can read is refused, never read as agreement")

        io.open(props, "w", encoding="utf-8").write("<Project></Project>\n")
        out = run()
        check(out["refused"] == "NO_MATRIX",
              "a props file naming no release is refused - an empty matrix "
              "agrees with every baseline there is")

        write_props("net48")
        out = RGR.regression(golden=os.path.join(where, "nowhere", "m.json"),
                             props=props, update=True)
        reached.add(out.get("refused"))
        check(out["refused"] == "CANNOT_WRITE",
              "a baseline that cannot be written says so")

        contract = CON.load(os.path.join(ROOT, "brain", "agents",
                                         "HERON-DEV-RGR-014.yaml"))
        declared = set(contract["failures"])
        check(declared <= reached,
              "every failure the contract declares is reached: missing %s"
              % (sorted(declared - reached) or "none"))
        check(reached - {None} <= declared,
              "and nothing is refused that the contract does not declare: "
              "extra %s" % (sorted((reached - {None}) - declared) or "none"))

    finally:
        shutil.rmtree(where, ignore_errors=True)

    print("\n%d checked, %d failed" % (len(CHECKED), len(FAILURES)))
    if FAILURES:
        for one in FAILURES:
            print("  FAILED  %s" % one)
        return 1
    print("\nThe matrix is read, compared and never quietly rewritten.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
